import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/ui/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${inter.className} antialiased text-gray-900`}>
        {children}

        {/* Footer, to be implemented in the future */}
        {/* <p className="absolute inset-x-0 bottom-0 text-center">Footer</p> */}
      </body>
    </html>
  );
}
